#line 2 "cpp_scanner_l.cpp"

#line 4 "cpp_scanner_l.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CppFlexScanner::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[232] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   70,   68,   68,   67,   68,    3,   50,   68,
       41,   42,   49,   48,   68,   68,   34,   34,   54,   47,
       45,   51,   46,   66,   66,   43,   44,   68,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   39,   40,   68,
        9,   68,   56,   57,   60,    3,   60,   56,   58,   59,
       56,   60,   61,   62,   65,    3,   63,   64,   65,   61,
       61,   65,   13,   14,   16,   16,    4,    6,    8,    7,
        8,    8,   12,   11,   12,   12,    0,    0,   67,    0,
        0,    0,   37,    2,   38,   33,    0,   34,    0,   34,

       53,   66,    3,    0,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,    0,    0,    0,
       56,   57,    3,   56,   61,   62,    3,   61,   13,   14,
       15,    4,    6,    5,    0,   11,    0,    0,   10,    0,
       52,   35,   55,    0,   37,   37,    0,   38,   33,    0,
       36,   32,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,    0,    1,    0,    0,
       37,    0,   37,    0,   38,   36,   32,   66,   66,   66,
       21,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,    0,   37,   27,   19,   18,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   22,   66,   28,   66,   66,
       66,   24,   20,   66,   66,   66,   66,   66,   23,   66,
       66,   29,   66,   26,   66,   66,   30,   31,   17,   25,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   12,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   25,
       26,   26,   26,   26,   26,   27,   26,   26,   26,   26,
       26,   26,   26,   26,   28,   26,   26,   29,   26,   26,
       30,   31,   32,   33,   26,    1,   34,   35,   36,   37,

       38,   39,   26,   40,   41,   26,   26,   42,   43,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   26,   29,
       52,   26,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    2,    2,    3,    1,    1,    4,    5,    5,
        6,    1,    1,    1,    7,    8,    8,    1,    1,    1,
        1,    1,    8,    8,    8,    9,    9,    9,    9,    1,
        3,    1,    1,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   10,   10
    } ;

static yyconst flex_int16_t yy_base[246] =
    {   0,
        0,   53,   57,   61,   70,   89,   66,   78,   97,  102,
       92,  114,  477,  478,   65,  478,  473,  478,  478,  444,
      478,  478,  478,  478,  105,  463,  132,  108,  455,  478,
      478,  478,  478,    0,   82,  478,  478,  454,   93,  427,
      423,  435,   62,  419,   19,  423,  425,  478,  478,  124,
      478,  119,    0,  478,  462,    0,  453,  458,  478,  478,
      129,  121,    0,  478,  459,    0,  478,  478,  450,  455,
      138,  132,    0,  478,  456,  443,    0,  478,  454,  478,
      478,  451,  147,  478,  452,  154,  150,  436,  478,  133,
      159,  439,  156,  478,  172,  201,  159,  127,    0,    0,

      478,    0,  478,  421,  402,  416,  405,  398,  406,  403,
      145,  410,  397,  400,  372,  374,  367,  185,  393,  162,
        0,  478,    0,  177,    0,  478,    0,  189,    0,  478,
      478,    0,  478,  478,  202,  478,  401,  204,  478,  396,
      478,  478,  478,  204,  478,  207,  210,  478,  210,  185,
      231,  213,  361,  346,  342,  342,  337,  282,  268,  268,
      274,  265,  268,  275,  267,  262,  209,  478,  307,  237,
      249,  245,  478,  251,  255,  478,  250,  269,  260,  258,
        0,  261,  255,  268,  263,  258,  262,  251,  242,  246,
      239,  267,  279,    0,    0,    0,  250,  239,  232,  239,

      233,  215,  225,  212,  210,    0,  208,    0,  202,  192,
      170,    0,    0,  160,  154,  141,  121,   93,    0,   82,
       65,    0,   48,    0,   40,   21,    0,    0,    0,    0,
      478,  321,  331,  341,  351,  361,  371,  374,  383,  392,
      402,  412,  422,   48,  432
    } ;

static yyconst flex_int16_t yy_def[246] =
    {   0,
      231,    1,  232,  232,  233,  233,  234,  234,  235,  235,
      236,  236,  231,  231,  231,  231,  231,  231,  231,  237,
      231,  231,  231,  231,  231,  231,  231,   27,  231,  231,
      231,  231,  231,  238,  238,  231,  231,  231,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  231,  231,  231,
      231,  231,  239,  231,  231,  239,  231,  239,  231,  231,
      239,  231,  240,  231,  231,  240,  231,  231,  231,  240,
      240,  231,  241,  231,  231,  231,  242,  231,  231,  231,
      231,  231,  243,  231,  231,  243,  231,  231,  231,  237,
      237,  231,  231,  231,  231,  231,  231,  231,  244,   28,

      231,  238,  231,  237,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  231,  231,  245,
      239,  231,  239,  239,  240,  231,  240,  240,  241,  231,
      231,  242,  231,  231,  243,  231,  231,  243,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  244,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  245,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  231,  231,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
        0,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231
    } ;

static yyconst flex_int16_t yy_nxt[533] =
    {   0,
       14,   15,   16,   17,   18,   14,   19,   20,   21,   22,
       23,   14,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   34,   34,   34,   35,   34,   34,   36,
       14,   37,   38,   34,   34,   39,   34,   40,   41,   34,
       34,   34,   34,   42,   34,   43,   34,   44,   45,   46,
       47,   34,   48,   49,   50,  152,  114,  230,   51,   54,
       55,   56,   61,   54,   55,   56,   87,   52,   74,   75,
      115,   57,   64,   65,   66,   62,   76,  229,   67,   68,
       74,   75,   88,   58,   69,  228,  103,   58,   76,  104,
       71,   64,   65,   66,   84,   85,   70,   67,   68,   78,

       79,   80,  227,   72,   78,   79,   80,   81,  111,   59,
       60,  112,   81,   59,   60,   70,   84,   85,   92,  226,
       93,   93,   86,  100,  100,  118,  105,   82,  225,   94,
      124,   94,   82,  120,  106,  120,  231,  107,  119,  128,
      142,   88,   94,  119,   86,   95,  120,   96,   96,  136,
      137,   87,  119,   98,   98,   97,  139,  140,   98,   98,
       99,  231,  224,   91,  168,  169,   90,   88,   98,   97,
      150,   93,   93,   98,  151,  151,   98,  138,  124,  144,
      145,   98,  145,  223,  138,  159,  118,  146,  146,  160,
      128,  119,  222,  144,  145,  147,  148,  145,  148,  119,

      151,  151,   88,  119,  136,  137,  139,  140,  221,  147,
      148,  168,  169,  148,   95,  170,   96,   96,  220,  171,
      171,  174,  146,  146,   97,  175,  175,  149,  149,  219,
      172,  173,  138,  173,  138,  218,  149,  149,   97,  177,
      177,  217,  149,  216,  172,  173,  151,  151,  173,  215,
      149,  149,  171,  171,  177,  176,  192,  176,  214,  149,
      193,  193,  177,  213,  171,  171,  175,  175,  212,  176,
      175,  175,  176,  145,  211,  145,  177,  177,  204,  148,
      210,  148,  193,  193,  209,  205,  208,  145,  207,  206,
      145,  177,  203,  148,  193,  193,  148,  202,  201,  177,

      200,  199,  198,  173,  197,  173,  196,  195,  194,  168,
      191,  190,  189,  188,  187,  186,  185,  173,  184,  183,
      173,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   90,   90,   90,  182,   90,   90,   90,   90,   90,
       90,  102,  102,  121,  181,  121,  121,  121,  121,  180,
      121,  121,  125,  179,  125,  125,  178,  125,  139,  125,

      125,  125,  129,  136,  129,  129,  129,  120,  129,  129,
      129,  129,  132,  166,  165,  132,  132,  164,  132,  132,
      132,  132,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  163,  162,  161,  158,  157,  156,  155,  154,
      153,   91,  143,  141,  136,  134,  133,  131,  130,  127,
       94,  126,  123,   94,  122,  117,  116,  113,  110,  109,
      108,   88,  101,   94,   91,   89,  231,   13,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231
    } ;

static yyconst flex_int16_t yy_chk[533] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,  244,   45,  226,    2,    3,
        3,    3,    4,    4,    4,    4,   15,    2,    7,    7,
       45,    3,    5,    5,    5,    4,    7,  225,    5,    5,
        8,    8,   15,    3,    5,  223,   35,    4,    8,   35,
        6,    6,    6,    6,   11,   11,    5,    6,    6,    9,

        9,    9,  221,    6,   10,   10,   10,    9,   43,    3,
        3,   43,   10,    4,    4,    6,   12,   12,   25,  220,
       25,   25,   11,   28,   28,   50,   39,    9,  218,   52,
       61,   62,   10,   52,   39,   62,   28,   39,   50,   71,
       90,   50,   72,   61,   12,   27,   72,   27,   27,   83,
       83,   87,   71,   98,   98,   27,   86,   86,   27,   27,
       27,   91,  217,   90,  120,  120,   91,   87,   98,   27,
       97,   93,   93,   27,   97,   97,   98,   83,  124,   93,
       93,   27,   93,  216,   86,  111,  118,   95,   95,  111,
      128,  124,  215,   93,   93,   95,   95,   93,   95,  118,

      150,  150,  118,  128,  135,  135,  138,  138,  214,   95,
       95,  167,  167,   95,   96,  144,   96,   96,  211,  144,
      144,  147,  146,  146,   96,  147,  147,   96,   96,  210,
      146,  146,  135,  146,  138,  209,  149,  149,   96,  152,
      152,  207,   96,  205,  146,  146,  151,  151,  146,  204,
       96,  149,  170,  170,  152,  151,  172,  151,  203,  149,
      172,  172,  152,  202,  171,  171,  174,  174,  201,  151,
      175,  175,  151,  171,  200,  171,  177,  177,  189,  175,
      199,  175,  192,  192,  198,  189,  197,  171,  191,  190,
      171,  177,  188,  175,  193,  193,  175,  187,  186,  177,

      185,  184,  183,  193,  182,  193,  180,  179,  178,  169,
      166,  165,  164,  163,  162,  161,  160,  193,  159,  158,
      193,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  237,  237,  237,  157,  237,  237,  237,  237,  237,
      237,  238,  238,  239,  156,  239,  239,  239,  239,  155,
      239,  239,  240,  154,  240,  240,  153,  240,  140,  240,

      240,  240,  241,  137,  241,  241,  241,  119,  241,  241,
      241,  241,  242,  117,  116,  242,  242,  115,  242,  242,
      242,  242,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  114,  113,  112,  110,  109,  108,  107,  106,
      105,  104,   92,   88,   85,   82,   79,   76,   75,   70,
       69,   65,   58,   57,   55,   47,   46,   44,   42,   41,
       40,   38,   29,   26,   20,   17,   13,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "cpp_scanner.l"
#line 2 "cpp_scanner.l"
#include "cpp_scanner_flex.h"
#define YY_NO_UNISTD_H 1
#line 14 "cpp_scanner.l"
#define YY_USER_ACTION  yylloc->columns(yyleng);





#line 631 "cpp_scanner_l.cpp"

#define INITIAL 0
#define FUNCTION 1
#define PARAMETERS 2
#define COMMENT 3
#define STRING 4
#define PREPROCESSOR 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "cpp_scanner.l"


#line 747 "cpp_scanner_l.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 232 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 231 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 37 "cpp_scanner.l"
{
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "cpp_scanner.l"
{
  comment_state = YYSTATE;
  BEGIN(COMMENT);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "cpp_scanner.l"
{
  comment_state = YYSTATE;
  BEGIN(STRING);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "cpp_scanner.l"
{
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "cpp_scanner.l"
{
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 56 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "cpp_scanner.l"
{
  BEGIN(comment_state);
  return CppBisonParser::token::STRINGVALUE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "cpp_scanner.l"
{
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "cpp_scanner.l"
{
  BEGIN(PREPROCESSOR);
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 75 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 80 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
  BEGIN(INITIAL);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "cpp_scanner.l"
{
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "cpp_scanner.l"
{
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 92 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "cpp_scanner.l"
{
  BEGIN(comment_state);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "cpp_scanner.l"
{
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "cpp_scanner.l"
{ return CppBisonParser::token::NAMESPACE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "cpp_scanner.l"
{ return CppBisonParser::token::CONST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "cpp_scanner.l"
{ return CppBisonParser::token::CLASS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "cpp_scanner.l"
{ return CppBisonParser::token::STRUCT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "cpp_scanner.l"
{ return CppBisonParser::token::ENUM; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "cpp_scanner.l"
{ return CppBisonParser::token::UNION; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "cpp_scanner.l"
{ return CppBisonParser::token::PRIVATE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "cpp_scanner.l"
{ return CppBisonParser::token::PUBLIC; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "cpp_scanner.l"
{ return CppBisonParser::token::PROTECTED; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "cpp_scanner.l"
{ return CppBisonParser::token::VIRTUAL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "cpp_scanner.l"
{ return CppBisonParser::token::CATCH; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "cpp_scanner.l"
{ return CppBisonParser::token::FRIEND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "cpp_scanner.l"
{ return CppBisonParser::token::TYPEDEF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 117 "cpp_scanner.l"
{ return CppBisonParser::token::TEMPLATE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 118 "cpp_scanner.l"
{ return CppBisonParser::token::TYPENAME; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "cpp_scanner.l"
{ 
  yylval->intvalue = std::strtol(yytext, 0, 16); 
  return CppBisonParser::token::INTVALUE; 
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "cpp_scanner.l"
{
  std::strtol(yytext, 0, 8);
  return CppBisonParser::token::INTVALUE; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "cpp_scanner.l"
{
  yylval->intvalue = std::atoi(yytext); 
  return CppBisonParser::token::INTVALUE; 
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 135 "cpp_scanner.l"
{
  std::strtol(yytext + 1, 0, 0);
  return CppBisonParser::token::INTVALUE; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "cpp_scanner.l"
{ 
  return CppBisonParser::token::FLOATVALUE; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "cpp_scanner.l"
{ 
  return CppBisonParser::token::FLOATVALUE; 
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 149 "cpp_scanner.l"
{ 
  return CppBisonParser::token::FLOATVALUE; 
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "cpp_scanner.l"
{ return '{'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "cpp_scanner.l"
{	return '}'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "cpp_scanner.l"
{ return '('; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 156 "cpp_scanner.l"
{ return ')';	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 157 "cpp_scanner.l"
{ return '['; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 158 "cpp_scanner.l"
{ return ']';	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 159 "cpp_scanner.l"
{ return '<'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 160 "cpp_scanner.l"
{	return '>'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 161 "cpp_scanner.l"
{ return ';'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "cpp_scanner.l"
{ return ','; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 163 "cpp_scanner.l"
{ return '*'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 164 "cpp_scanner.l"
{ return '&'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 165 "cpp_scanner.l"
{ return '='; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 167 "cpp_scanner.l"
{ 
  return CppBisonParser::token::UNQUALIFIER;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 171 "cpp_scanner.l"
{ 
  return CppBisonParser::token::QUALIFIER;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 175 "cpp_scanner.l"
{ return ':'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 177 "cpp_scanner.l"
{ 
  return CppBisonParser::token::THREEDOT;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 181 "cpp_scanner.l"
{
}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 184 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 189 "cpp_scanner.l"
{
    ++bracket_level;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 193 "cpp_scanner.l"
{
    --bracket_level;
    if (bracket_level == 0)
    {
      BEGIN(INITIAL);
		  yylval->ident = std::string(yytext, yyleng); 
		  return CppBisonParser::token::FUNCTION_BODY;
    }
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 203 "cpp_scanner.l"
{
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "cpp_scanner.l"
{
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 209 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 214 "cpp_scanner.l"
{
    ++bracket_level;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 218 "cpp_scanner.l"
{
    --bracket_level;
    if (bracket_level == 0)
    {
      BEGIN(INITIAL);
		  yylval->ident = std::string(yytext, yyleng); 
		  return CppBisonParser::token::PARAMETER_LIST;
    }
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 228 "cpp_scanner.l"
{
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 233 "cpp_scanner.l"
{ 
		yylval->ident = std::string(yytext, yyleng); 
		return CppBisonParser::token::IDENT;
}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 238 "cpp_scanner.l"
{
  yylloc->lines(1);
  yylloc->step();
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 243 "cpp_scanner.l"
{ 
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 247 "cpp_scanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1275 "cpp_scanner_l.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FUNCTION):
case YY_STATE_EOF(PARAMETERS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(PREPROCESSOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 232 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 232 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 231);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 247 "cpp_scanner.l"



